version: "3.8"

services:
  backend:
    container_name: backend
    image: arturdzh/docker-project-backend:latest
    networks:
      - internal

  frontend:
    container_name: frontend
    image: arturdzh/docker-project-frontend:latest
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - internal

networks:
  internal:
    external: false
