version: "3.8"

services:
  backend:
    container_name: backend
    image: arturdzh/docker-project-backend:latest
    ports:
      - "8081:8081"

  frontend:
    container_name: frontend
    image: arturdzh/docker-project-frontend:latest
    ports:
      - "80:80"
    # environment:
    #   - NODE_OPTIONS=--openssl-legacy-provider
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./fronend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
