name: Docker Project Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_push_to_docker_hub:
      name: Push Docker image to DockerHub
      runs-on: ubuntu-latest
      steps:
        - name: Check out the repo
          uses: actions/checkout@v3
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        - name: Login to Docker 
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        - name: Push Backend to DockerHub
          uses: docker/build-push-action@v4
          with:
            context: ./backend/
            push: true
            tags: ${{ secrets.DOCKER_USER }}/docker-project-backend:latest
        - name: Push Frontend to DockerHub
          uses: docker/build-push-action@v4
          with:
            context: ./frontend/
            push: true
            tags: ${{ secrets.DOCKER_USER }}/docker-project-frontend:latest

  run-with-docker-compose:
    name: Push Docker image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Create example secret file (for validation only)
        run: echo "example" > my_secret
      - name: Build via Docker Compose
        uses: hoverkraft-tech/compose-action@v2.2.0

  trivy:
    runs-on: ubuntu-latest
    needs: [build_and_push_to_docker_hub, run-with-docker-compose]
    strategy:
      matrix:
        image:
          - arturdzh/docker-project-frontend:latest
          - arturdzh/docker-project-backend:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
          sudo mv ./bin/trivy /usr/local/bin/

      - name: Scan image with Trivy
        run: |
          IMAGE="${{ matrix.image }}"
          SAFE_NAME=$(echo "$IMAGE" | tr '/:' '_')
          trivy image --exit-code 0 --format json -o trivy_${SAFE_NAME}.json "$IMAGE"

      - name: Generate safe artifact name
        id: artifact-name
        run: |
          SAFE_NAME=$(echo "${{ matrix.image }}" | tr '/:' '_')
          echo "safe_name=$SAFE_NAME" >> $GITHUB_OUTPUT

      - name: Upload Trivy report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-${{ steps.artifact-name.outputs.safe_name }}
          path: trivy-report.json
  
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: trivy
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Copy project to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERSERV }}
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: "/home/user/project"

      - name: Executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERSERV }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/user/project/ 
            sudo docker-compose -f docker-compose.prod.yml pull
            sudo docker-compose -f docker-compose.prod.yml down
            sudo docker-compose -f docker-compose.prod.yml up -d --scale backend=3
